### ISSUE TITLE
貌似会出现这个断言失败

### ISSUE THREAD

**Issue by LouisLou2** [ceresOPA/Automatic-Sleep-Staging-Based-on-EEG-Signal-using-Deep-Network#1]
Traceback (most recent call last):
  File "D:\Tools\PyCharm 2023.1.4\plugins\python\helpers\pydev\pydevd.py", line 1500, in _exec
    pydev_imports.execfile(file, globals, locals)  # execute the script
  File "D:\Tools\PyCharm 2023.1.4\plugins\python\helpers\pydev\_pydev_imps\_pydev_execfile.py", line 18, in execfile
    exec(compile(contents+"\n", file, 'exec'), glob, loc)
  File "D:\SourceCode\EEG\Automatic-Sleep-Staging-Based-on-EEG-Signal-using-Deep-Network\prepare_data.py", line 29, in <module>
    x, y = edf2numpy(signal_file, annotation_file, ["EEG Fpz-Cz"])
  File "D:\SourceCode\EEG\Automatic-Sleep-Staging-Based-on-EEG-Signal-using-Deep-Network\preprocessing.py", line 67, in edf2numpy
    assert signals.shape[0] == n_epochs, f"signal: {signals.shape} != {n_epochs}"
AssertionError: signal: (79500, 100) != 2650

**Comment by ceresOPA** [comment]
这是对样本个数的判断，n_epochs是指按30s的片段切分后的样本个数，signals一般会分为(n_epochs, dim)，dim是你的30s的一个采样点的个数

**Comment by GritYolo** [comment]
我也遇到了相同的问题，
请问大佬你是怎么解决的呢？How do you solve the problem？

**Comment by xcf11111** [comment]
在preprocessing 67行改成assert signals.shape[0] // X_data.datarecord_duration == n_epochs, f"signal: {signals.shape} != {n_epochs}"
